import {NgModule} from '@angular/core';
import {
    ConferenceIDPipe, ConferenceNamePipe,
    ConferencePipe,
    ConferenceRankPipe, DivisionAbbreviationPipe, DivisionIDPipe, DivisionNamePipe, DivisionNameShortPipe, DivisionPipe,
    DivisionRankPipe,
    GoalsAgainstPipe, LeagueIdentifierIDPipe, LeagueIdentifierNamePipe, LeagueIdentifierPipe,
    LeagueRankPipe,
    LeagueRecordLossesPipe, LeagueRecordOTPipe, LeagueRecordWinsPipe,
    PointsPipe, StandingsPipe, StreakCodePipe, StreakNumberPipe, StreakTypePipe
} from './standings/standings.pipe';

@NgModule({
    declarations: [
        ConferencePipe,
        ConferenceIDPipe,
        ConferenceNamePipe,
        ConferenceRankPipe,
        DivisionPipe,
        DivisionAbbreviationPipe,
        DivisionIDPipe,
        DivisionNamePipe,
        DivisionNameShortPipe,
        DivisionRankPipe,
        GoalsAgainstPipe,
        LeagueIdentifierIDPipe,
        LeagueIdentifierNamePipe,
        LeagueIdentifierPipe,
        LeagueRankPipe,
        LeagueRecordWinsPipe,
        LeagueRecordLossesPipe,
        LeagueRecordOTPipe,
        PointsPipe,
        StandingsPipe,
        StreakTypePipe,
        StreakNumberPipe,
        StreakCodePipe],
    exports: [
        ConferencePipe,
        ConferenceIDPipe,
        ConferenceNamePipe,
        ConferenceRankPipe,
        DivisionPipe,
        DivisionAbbreviationPipe,
        DivisionIDPipe,
        DivisionNamePipe,
        DivisionNameShortPipe,
        DivisionRankPipe,
        GoalsAgainstPipe,
        LeagueIdentifierIDPipe,
        LeagueIdentifierNamePipe,
        LeagueIdentifierPipe,
        LeagueRankPipe,
        LeagueRecordWinsPipe,
        LeagueRecordLossesPipe,
        LeagueRecordOTPipe,
        PointsPipe,
        StandingsPipe,
        StreakTypePipe,
        StreakNumberPipe,
        StreakCodePipe],
})
export class PipesModule {
}